name: ItemRecovery
version: '${project.version}'
main: tech.justcoding.itemrecovery.Main
api-version: 1.18
libraries:
  - org.postgresql:postgresql:42.3.1
commands:
  recovery:
    description: File a recovery notice.